- name: Clone blog repository
  git:
    repo: https://github.com/cw-barry/blog-app-MERN.git
    dest: /home/ubuntu/blog-app
  become_user: ubuntu

- name: Generate .env file
  template:
    src: env.j2
    dest: /home/ubuntu/blog-app/backend/.env
    owner: ubuntu
    mode: '0644'

- name: Install npm dependencies
  npm:
    path: /home/ubuntu/blog-app/backend
    state: present
  become_user: ubuntu

- name: Create logs directory
  file:
    path: /home/ubuntu/blog-app/backend/logs
    state: directory
    owner: ubuntu

- name: Start backend with PM2
  shell: |
    . /home/ubuntu/.nvm/nvm.sh
    pm2 start index.js --name "blog-backend"
    pm2 save
  args:
    chdir: /home/ubuntu/blog-app/backend
  become_user: ubuntu
